### ISSUE TITLE
Errors probably due to geometry handling in debug mode

### ISSUE THREAD

**Issue by AnonymousGeniusProgrammer** [FreeCAD/FreeCAD-LibPack#4] opened 2022-10-10 12:54 UTC
Hi, dear FreeCAD Libpack maintainer, thanks for creating Libpacks for our convenience first! I have run into this error with the new FreeCAD Libpack for 020, the error occurs when I try to import a geometry or open a project file containing geometries, the screenshot of the error message please see below. 
- I am working on a windows 10 machine building FreeCAD in debug mode, I have tested different compilers, MSVC++ 14.2x and MSVC++ 14.3x, and they result in the same error
- I have tested the Libpack 12.5.4  from https://github.com/apeltauer/FreeCAD/releases here, I did not run into the same issue while importing geometries.
![image](https://user-images.githubusercontent.com/73345309/194861266-81c198d6-ab24-4de2-9404-f6569ec522b2.png)

**Comment by donovaly** [comment] 2022-10-13 23:55
Thanks for the report.
- What LibPack version did you use?
- Does the problem also occur with a release build?
- Do you have a step by step procedure to reproduce the issue please?

**Comment by RuoyuLiOT-DE** [comment] 2022-10-17 11:12
Thanks for your reply!
- I am using the LibPack-0.20 Version 2.7
- it only occurs with the debug build
- to reproduce:
  - build with debug mode
  - launch the debugger in VSCode
  - on the Start page, click the thumbnail of "Schenkel.stp" from Examples, and the error occurs

**Comment by donovaly** [comment] 2022-10-23 03:36
Thanks!
This seems to be a tricky issue. We changed many in the LibPack 2.x for the 0.20 release. And since release builds were the target, we did not test debug builds thoroughly yet. However I used debug builds already and did not yet encounter crashes.

I need to check with your recipe. Unfortunately I have no time right now (I am the release manager and have now to prepare the first toponaming test release). But I don't want to let you wait. Can you therefore also report this issue in  the developer's forum: https://forum.freecadweb.org/viewforum.php?f=10
Maybe someone else can reproduce the issue.

**Comment by RuoyuLiOT-DE** [comment] 2022-10-24 07:12
> Thanks! This seems to be a tricky issue. We changed many in the LibPack 2.x for the 0.20 release. And since release builds were the target, we did not test debug builds thoroughly yet. However I used debug builds already and did not yet encounter crashes.
> 
> I need to check with your recipe. Unfortunately I have no time right now (I am the release manager and have now to prepare the first toponaming test release). But I don't want to let you wait. Can you therefore also report this issue in the developer's forum: https://forum.freecadweb.org/viewforum.php?f=10 Maybe someone else can reproduce the issue.

ok! I will try that, thanks!

**Comment by donovaly** [comment] 2023-01-25 15:06
Does the error still exist?

I realized that the Wiki page: https://wiki.freecadweb.org/Compile_on_Windows#Running_and_installing_FreeCAD misses info that to run a debug build properly, one needs to do this:
- copy manually the content of LibPack-OCC76-V2\bind and LibPack-OCC76-V2\libd to the `bin`  and `lib` folder of the installation folder

**Comment by donovaly** [comment] 2023-01-25 15:21
I added the info to run a debug build to the Wiki: https://wiki.freecadweb.org/Compile_on_Windows#Debug_Build

**Comment by chennes** [comment] 2024-09-04 13:44
At present LibPack 3 only supports compiling in Release and RelWithDebInfo modes. We plan to add debug support in the future, pending getting a working debug build of numpy. I'm going to close this ticket since it related to LibPack 2, which is no longer supported.

**Closed by chennes** 2024-09-04 13:44 UTC
